import os
from distutils.core import setup

setup(
    name         = 'dovecot',
    version      = '2.0',
    author       = 'Fabien Benureau, Paul Fudal',
    author_email = 'fabien.benureau@inria.fr',
    description  = ('A python library to drive the hardware and simulation experiment of the author PhD thesis'),
    license      = 'Open Science',
    keywords     = 'science experiment hardware simulation robots',
    url          = 'flowers.inria.fr',
    packages = ['dovecot',
                'dovecot.logger',
                'dovecot.prims',
                'dovecot.ttts',
                'dovecot.ttts.files',
                'dovecot.kinsim',
                'dovecot.vrepsim',
                'dovecot.stemsim',
                'dovecot.stemsim',
                'dovecot.stemsim.stemcfg',
                'dovecot.collider',
                'dovecot.calibration',
                'dovecot.calibration.triocal',
                'dovecot.calibration.tttcal'
               ],
    classifiers = [],
    package_data = {'dovecot.ttts.files'    : ['vrep_center_cube.ttt',
                                                 'ar_center_cube.ttt',
                                               'vrep_center_sphere.ttt',
                                                 'ar_center_sphere.ttt',
                                               'vrep_cylinder.ttt',
                                                 'ar_cylinder.ttt',
                                               'vrep_other_cube.ttt',
                                                 'ar_other_cube.ttt',
                                               'vrep_center_cylinder.ttt',
                                                 'ar_center_cylinder.ttt',
                                               'vrep_calibrate.ttt',
                                               'ar.ttt'],
                    'dovecot.collider'      : ['stem.smodel'],
                    'dovecot.calibration.triocal' : ['calib0.data',
                                                     'calib1.data',
                                                     'calib2.data',
                                                     'calib3.data']}, # FIXME should be dynamic
)