"""
Code generated by pyforward 1.0
Author : Fabien Benureau (fabien.benureau+pyforward@gmail.com)

Denavit-Hartenberg parameters of the kinematic model :

    alpha	a	d	theta
    -------------------------------------
    -pi/2	0	a	t0
    0	b	0	t1 - pi/2
    pi/2	0	0	t2 + pi/2
    -pi/2	d	c	t3
    0	e	0	t4
    0	f	0	t5

with variables : t0, t1, t2, t3, t4, t5
 and constants : a, b, c, d, e, f

"""
from math import cos, sin, pi

# Constant values
a = 35
b = 82
c = 80
d = 65
e = 67
f = 80

deg2rad = pi/180.0
def forward_kin(t0, t1, t2, t3, t4, t5):
    return _forward_kin(-t0*deg2rad, t1*deg2rad, t2*deg2rad, -t3*deg2rad, t4*deg2rad, t5*deg2rad)

def _forward_kin(t0, t1, t2, t3, t4, t5):
    x =(0
      + b*sin(t1)*cos(t0)
      + 0
      + c*sin(t1 + t2)*cos(t0) - d*sin(t0)*sin(t3) + d*cos(t0)*cos(t3)*cos(t1 + t2)
      + e*(-sin(t0)*sin(t3)*cos(t4) - sin(t4)*sin(t1 + t2)*cos(t0) + cos(t0)*cos(t3)*cos(t4)*cos(t1 + t2))
      + f*(-sin(t0)*sin(t3)*cos(t4 + t5) - sin(t1 + t2)*sin(t4 + t5)*cos(t0) + cos(t0)*cos(t3)*cos(t1 + t2)*cos(t4 + t5))
       )

    y =(0
      + b*sin(t0)*sin(t1)
      + 0
      + c*sin(t0)*sin(t1 + t2) + d*sin(t0)*cos(t3)*cos(t1 + t2) + d*sin(t3)*cos(t0)
      + e*(-sin(t0)*sin(t4)*sin(t1 + t2) + sin(t0)*cos(t3)*cos(t4)*cos(t1 + t2) + sin(t3)*cos(t0)*cos(t4))
      + f*(-sin(t0)*sin(t1 + t2)*sin(t4 + t5) + sin(t0)*cos(t3)*cos(t1 + t2)*cos(t4 + t5) + sin(t3)*cos(t0)*cos(t4 + t5))
       )

    z =(a
      + b*cos(t1)
      + 0
      + c*cos(t1 + t2) - d*sin(t1 + t2)*cos(t3)
      - e*(sin(t4)*cos(t1 + t2) + sin(t1 + t2)*cos(t3)*cos(t4))
      - f*(sin(t1 + t2)*cos(t3)*cos(t4 + t5) + sin(t4 + t5)*cos(t1 + t2))
       )

    return (x, y, z)